// AssertionError
// ==============
//
// Represents an error generated by a passive assertion (the example's return
// value)
"use strict";

var AssertionError = function (message) {

  //! Set the error message
  this.message = message

  //! Set the name. Used for logging the stack trace
  this.name    = "AssertionError"

  //! Get the stack trace from Error
  //! This is a weird thing to do but it turns out that it is the only
  //! way around
  Error.captureStackTrace(this, AssertionError)
}

//! Inherit from Error
AssertionError.prototype = Object.create(Error.prototype)

module.exports = AssertionError
