// TimeoutError
// ============
//
// Represents an error generated by timeout
"use strict"

var TimeoutError = function (message) {
  this.message = message
  this.name    = "TimeoutError"

  Error.captureStackTrace(this, TimeoutError)
}

TimeoutError.prototype = Object.create(Error.prototype)

module.exports = TimeoutError
