// TimeoutError
// ============
//
// Represents an error generated by timeout
"use strict"

var TimeoutError = function (message) {
  this.message = message
}

TimeoutError.prototype = Object.create(Error.prototype)

module.exports = TimeoutError
